Gemfile
Gemfile.lock
config/unicorn.rb

unicorn.rb作成
gem unicorn　導入
デプロイ環境構築のため

[WIP]cleate_unicorn.rb

---

config/database.yml

database.yml編集
#Why
デプロイ環境構築のため

[WIP]edit_database.yml

---

config/routes.rb

[WIP]rooting_test

---

Gemfile
Gemfile.lock
app/assets/stylesheets/_reset.scss
app/assets/stylesheets/application.scss
config/routes.rb

[WIP]0910_各種設定

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/config/_colors.scss
app/assets/stylesheets/mixins/_mixin.scss

sassで使用する変数の定義
今後繰り返し使うと思われる色などを変数にしておくと効率的なため

Variabledefinition

---

README.md

README.mdへDB設計記載

---

config/unicorn.rb

unicorn.rb編集
#Why
自動デプロイ実装のためのファイル編集

[WIP]unicorn.rb　編集

---

Capfile
Gemfile
Gemfile.lock
config/deploy.rb
config/deploy/production.rb
config/deploy/staging.rb
config/environments/production.rb
config/unicorn.rb

自動デプロイ設定のためのファイル編集
自動デプロイ機能実装のため

[WIP]自動デプロイtest

---

app/controllers/application_controller.rb
config/deploy/production.rb

ベーシック認証機能追加（本番環境のみ）
開発メンバー以外がログインできないようにするため

[WIP]cleate_basic_authentication

---

config/deploy.rb

[WIP]ベーシック認証本番環境追加

---

app/assets/stylesheets/modules/_devise.scss
app/views/devise/registrations/new.html.haml

新規登録画面(会員情報入力)のマークアップを行いました。
必要な画面であるため。

新規登録画面（会員情報入力）のマークアップ

---

app/assets/javascripts/cards.coffee
app/assets/stylesheets/cards.scss
app/controllers/cards_controller.rb
app/helpers/cards_helper.rb
config/routes.rb
test/controllers/cards_controller_test.rb

cards controller
付随するviewの作成
ビューのマークアップのため

[WIP]cleate_cards_controller&view

---

app/views/devise/registrations/new.html.haml
app/views/devise/sessions/new.html.haml
app/views/shared/_sub_footer.html.haml
app/views/shared/_sub_header.html.haml

サブフッダーとサブヘッダーの部分テンプレート化。
複数のページで共有できる部分が存在するため。

部分テンプレート化(サブヘッダー・サブフッダー)

---

app/assets/stylesheets/modules/_items.scss

画像がはみ出るのを修正

---

app/assets/stylesheets/modules/_items.scss

[WIP]right_space_correction_conplate

---

app/assets/stylesheets/modules/_devise.scss
app/controllers/users_controller.rb
app/views/users/phone.html.haml
config/routes.rb

新規登録画面の携帯電話番号入力フォームを作成した。
必要なページであるため。

携帯電話番号の入力フォームのビュー作成

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/modules/_profile.scss
app/controllers/users_controller.rb
app/views/users/profile.html.haml
config/routes.rb

profile-create

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/modules/_main_footer_image.scss
app/assets/stylesheets/modules/_users.scss
app/views/shared/_main_footer_image.html.haml
app/views/shared/_mypage-user-info-todo.html.haml
app/views/users/show.html.haml

マイページ微修正
フッターのイメージ画像のテンプレート化
フッターイメージは多くのビューで必要のため

[WIP]cleate_mypage2微修正1

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/modules/_logout.scss
app/controllers/users_controller.rb
app/views/users/logout.html.haml
config/routes.rb

logout-view

---

app/views/cards/create.html.haml

新規登録完了ページのビュー作成

---

db/migrate/20190916092518_change_column_to_not_null.rb
db/migrate/20190916093645_change_column_to_not_null_addresses.rb
db/migrate/20190916094627_change_column_to_not_nullcreditcards.rb
db/schema.rb

addressテーブル、creditcardテーブルの制約変更
データベース設計の変更

[WIP]addresses,creditcard制約変更

---

db/migrate/20190916102351_add_creditcard_to_users.rb
db/migrate/20190916104732_remove_purchase_from_items.rb
db/schema.rb

usersテーブルにcreditcardカラム追加
itemsテーブルにpurchase_idカラム削除
データベース設計変更

[WIP]カラム追加、削除

---

app/assets/stylesheets/modules/_header.scss
app/views/shared/_header.html.haml

login-btn-create

---

app/assets/stylesheets/modules/_cards.scss
app/views/cards/index.html.haml
app/views/cards/new.html.haml
app/views/users/logout.html.haml
app/views/users/profile.html.haml

ログアウト画面、プロフィール画面、クレジットindex,new画面のサイドバー追加

add-side-ber-edit

---

README.md

phone_numberの型をstringに修正
int型だと数値なので0から始まる電話番号が保存できないため

usersテーブルのphone_numberの型をstringに編集

---

app/views/shared/_header.html.haml

header-edit

---

README.md

pictureテーブルのuser_idカラム削除
filds_forによる画像登録のためにuser_idを削除

pictureテーブルreadme変更

---

app/controllers/cards_controller.rb
app/views/cards/destroy.html.haml
app/views/cards/show.html.haml
config/routes.rb

ユーザが登録しているクレジットカード情報を表示する。
必要な機能のため。

ユーザのクレジットカード情報表示

---

app/controllers/items_controller.rb
app/views/items/show.html.haml

商品削除機能実装
メルカリに必要な機能のため。
コメントアウトの部分はログイン機能を実装後に表示する予定です。

【サーバサイド】商品削除

---

app/assets/javascripts/category.js
app/assets/javascripts/delivery.js
app/assets/stylesheets/modules/_items-new.scss
app/controllers/items_controller.rb
app/models/delivery.rb
app/models/item.rb
app/views/items/get_category_children.json.jbuilder
app/views/items/get_delivery_children.json.jbuilder
app/views/items/new.html.haml
config/routes.rb
db/migrate/20190924105915_remove_responsibility_from_items.rb
db/migrate/20190924110022_add_details_to_items.rb
db/migrate/20190924110150_create_deliveries.rb
db/migrate/20190924110422_add_ancestry_to_deliveries.rb
db/migrate/20190924114908_add_delivery_ref_to_items.rb
db/schema.rb
db/seeds.rb
spec/factories/deliveries.rb
spec/models/delivery_spec.rb

発送料の負担の選択を実装

---

app/assets/stylesheets/modules/_items-new.scss
app/controllers/items_controller.rb
app/models/item.rb
app/models/picture.rb
app/views/items/new.html.haml

[WIP]画像複数枚投稿２

---

app/models/item.rb
app/views/cards/index.html.haml
app/views/items/show.html.haml
app/views/shared/_content.html.haml
app/views/shared/_header.html.haml
app/views/shared/_mypage-side-manu.html.haml

link_toの設定

---

app/assets/stylesheets/modules/_items-show.scss
app/controllers/items_controller.rb
app/views/items/show.html.haml

【サーバサイド】商品詳細の実装
itemに紐つくデータを表示する機能を実装しました。
ブランドや配送方法などはまだテーブルにないので、実装後に別途プルリクさせていただきたいです。

0926_商品詳細一旦完了

---

app/controllers/cards_controller.rb
app/views/cards/show.html.haml

クレジットカード情報の削除機能実装

---

app/controllers/items_controller.rb
app/models/item.rb
app/views/shared/_mypage-side-manu.html.haml
app/views/shared/_sell-btn.html.haml
db/migrate/20190912045322_create_items.rb
db/migrate/20190912070426_add_item_id_to_purchases.rb
db/migrate/20190916104732_remove_purchase_from_items.rb
db/migrate/20190925055015_remove_user_id_from_purchases.rb
db/migrate/20190925055247_add_user_ref_to_purchase.rb
db/migrate/20190925060152_change_data_status_to_purchase.rb
db/migrate/20190925063036_remove_user_from_purchases.rb
db/migrate/20190926014815_destory_purchases_table.rb
db/schema.rb

出品画面での必要事項の保存
マイグレーションファイルの編集
buyer_idをカラムに追加したら保存できない不具合が発生したため
マイグレーションファイルのリセットをかけたらreferenceではなくbigintにしろとエラーが出たため

[WIP]マイグレーションファイルの編集、商品出品機能実装

---

app/assets/stylesheets/modules/_information.scss
app/controllers/addresses_controller.rb
app/views/users/information.html.haml

本人情報の登録画面にアクティブハッシュで都道府県を選択できるように修正
都道府県選択を楽にするため

Edit registration of personal information

---

app/assets/javascripts/payjp.js
app/controllers/addresses_controller.rb

ボタン押下後、非活性にしない記述に変更
スプリントレビューの際に指摘があったため

クレジットカード登録画面

---

app/assets/stylesheets/modules/_exhibit_now.scss
app/assets/stylesheets/modules/_items-new.scss
app/controllers/items_controller.rb
app/controllers/users_controller.rb
app/views/items/new.html.haml
app/views/shared/_exhibit-now.html.haml

[WIP]商品出品編集微修正

---

app/views/cards/create.html.haml
db/schema.rb

ユーザ新規登録完了画面のリンク設定
スプリントレビューの際に指摘があったため

ユーザ新規登録完了画面のリンク設定

---

app/views/shared/_footer.html.haml
app/views/shared/_sub_header.html.haml

subheader,foorerのリンクの設定
外部のURLが設定されていたため"#"とrootに変更

Sub footerリンク設定

---

app/controllers/cards_controller.rb
app/views/addresses/new.html.haml

住所入力画面の誤字修正とエラー修正
ビューを整える、エラー解決のため

ビューとエラーの修正

---

app/assets/stylesheets/modules/_items-show.scss
app/views/items/buy.html.haml
app/views/items/show.html.haml

ユーザーの状態によるリンク先でのエラー修正
ユーザーのログイン、ログアウト、クレカ所持、なし、自分の商品、他人の商品でいろいろエラーがあったから

[WIP]エラー修正（詳細画面等）

---

app/views/shared/_mypage-side-manu.html.haml
db/schema.rb

マイページから出品画面へのリンク修正
パスが正しい表記ではなかったため

マイページから出品画面へのリンク修正

---

README.md
app/assets/stylesheets/modules/_information.scss
app/controllers/addresses_controller.rb
app/models/address.rb
app/views/addresses/new.html.haml
app/views/layouts/_error_messages.html.haml
config/routes.rb
db/migrate/20191002064951_change_datatype_postcode_of_addresses.rb
db/schema.rb
spec/factories/addresses.rb
spec/models/address_spec.rb
spec/models/user_spec.rb

住所を登録する際、不備があると登録できないようにバリデーションをかけ、単体テストを行った
間違った住所が登録されないようにするため

住所登録のバリデーションとテスト
